### ISSUE TITLE
Update project files to build

### ISSUE THREAD

**Issue by anhoavu** [Microsoft/App-Extensibility-Sample#3]
Please update the project configuration so that we can build it without further effort. I am getting

Error CS0246: The type or namespace name 'AssemblyTitleAttribute' could not be found (are you missing a using directive or an assembly reference?)

**Comment by dkbennett** [comment]
I updated the project to target the Anniversary Edition SDK, please see if that addresses your issue. Works for me as-is now on VS 2017
